version: "3.5"

services:
  app:
    image: golang:1.17-stretch
    ports:
      - ${DOCKER_HTTP_PORT}:80
    volumes:
      - ./:/go/src/app
      - ./data/go/pkg/mod:/go/pkg/mod
      - ./data/go/bin:/go/bin
    environment:
      - GO111MODULE=on
    working_dir: /go/src/app
    tty: true
  redis:
    image: redis:latest
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    command: --requirepass "${DOCKER_REDIS_PASSWORD}"
    volumes:
      - ./data/redis:/data
